//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mount_player.rc
//
#define IDSAVETOCACHE                   3
#define IDC_LAST_POINT                  5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_mount_playerTYPE            130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_MOUNT_LIGHT_DIALOG          312
#define IDR_BRIDGE_TOOLBAR              313
#define IDB_BITMAP1                     317
#define IDB_BRIDGE_TOOLBAR_BMP          317
#define IDD_VIRTUAL_MOUNT_DIALOG        318
#define IDD_LOCATION_DIALOG             319
#define IDD_SUBTITLE_INPUT_DIALOG       320
#define IDD_MAIN_SUB_STEP_DIALOG        322
#define IDD_MOVEMENT_LABEL_DIALOG       323
#define IDR_RBUTTON_MENU                325
#define IDR_TOOLBAR1                    332
#define IDR_PROPERS_TOOLBAR             332
#define IDR_TOOLBAR2                    334
#define IDR_PROPER_TOOLBAR              334
#define IDR_PROPERTY_TOOLBAR            336
#define IDC_SELECT_1_RADIO              1001
#define IDC_ENABLE_CHECK                1003
#define IDC_LIGHT_SLIDER                1004
#define IDC_PART_LIST                   1005
#define IDC_ABSOLUTE_RELATVE_CHECK2     1005
#define IDC_ABSOLUTE_RELATIVE_CHECK     1005
#define IDC_DX_EDIT                     1007
#define IDC_SEPARATE_SPE_CHECK          1007
#define IDC_SEPARATE_SPECULAR_CHECK     1007
#define IDC_DY_EDIT                     1008
#define IDC_DZ_EDIT                     1009
#define IDC_RX_EDIT                     1010
#define IDC_RY_EDIT                     1011
#define IDC_SELECT_2_RADIO              1012
#define IDC_RZ_EDIT                     1012
#define IDC_SELECT_3_RADIO              1013
#define IDC_MAIN_STEP_EDIT              1013
#define IDC_SELECT_4_RADIO              1014
#define IDC_SUB_STEP_EDIT               1014
#define IDC_SELECT_5_RADIO              1015
#define IDC_SUBTITLE_EDIT               1015
#define IDC_SELECT_6_RADIO              1016
#define IDC_SELECT_7_RADIO              1017
#define IDC_SELECT_8_RADIO              1018
#define IDC_SELECT_SELECTED_RADIO       1020
#define IDC_SELECT_BACKGROUND_RADIO     1021
#define IDC_X_EDIT                      1022
#define IDC_SELECT_ENVIRONMENT_RADIO    1023
#define IDC_Y_EDIT                      1024
#define IDC_Z_EDIT                      1025
#define IDC_SHININESS_EDIT              1026
#define IDC_SPECULAR_EDIT               1028
#define IDC_AMBIENT_EDIT                1029
#define IDC_DIFFUSE_EDIT                1030
#define IDC_EMISSION_EDIT               1031
#define IDC_RED_EDIT                    1032
#define IDC_GREEN_EDIT                  1033
#define IDC_BLUE_EDIT                   1034
#define IDC_COLOR_INPUT_BUTTON          1035
#define IDC_TIME_EDIT                   1036
#define IDC_CACHE_LABEL_EDIT            1037
#define IDC_MOVEMENT_LABEL_EDIT         1038
#define IDC_SAVE_TO_CACHE_CHECK         1039
#define MENU_HIDE_COMPONENT             32771
#define MENU_HIDE_BOLT                  32772
#define MENU_HIDE_ALL_COMPONENT         32773
#define MENU_CLEAR_HIDE_COMPONENT       32774
#define MENU_DISPLAY_BOX                32775
#define MENU_CLEAR_DISPLAY_BOX          32776
#define MENU_SET_COMPONENT_TRANSPARENT  32777
#define MENU_CLEAR_COMPONENT_TRANSPARENT 32778
#define MENU_UP_SELECTION               32779
#define MENU_DOWN_SELECTION             32780
#define MENU_SET_CLIP_PLANE             32781
#define MENU_CLEAR_CLIP_PLANE           32782
#define MENU_COMPONENTS_NUMBER_NAME     32783
#define MENU_LOCK_COMPONENT             32785
#define MENU_PUT_IN_VIEW                32786
#define MENU_PUT_IN_EQUAL_VIEW          32787
#define MENU_VIEW_X                     32788
#define MENU_VIEW_Y                     32789
#define MENU_VIEW_Z                     32790
#define MENU_BACKWARD_VIEW              32791
#define MENU_MODIFY_LIGHT               32792
#define MENU_PIN_POINT                  32793
#define MENU_INTERACT_TRANSLATION       32794
#define MENU_INTERACT_ROTATION          32795
#define MENU_INTERACT_ENLARGE_AREA      32796
#define MENU_INTERACT_SELECTION         32797
#define MENU_INTERACT_SCALE             32798
#define MENU_INTERACT_SPEED             32799
#define MENU_INTERACT_CLIP_PLANE        32800
#define MENU_INTERACT_COMPONENT_TRANSPARENCE 32801
#define MENU_INTERACT_MANUAL_MOUNT      32802
#define MENU_FORWARD_ONE                32805
#define MENU_FORWARD_ALL                32810
#define MENU_STOP_MOUNT                 32811
#define MENU_BACKWARD_ONE               32812
#define MENU_BACKWARD_ALL               32813
#define MENU_JUMP_STEP                  32815
#define MENU_PLAY_SOUND                 32817
#define MENU_CHANGE_VIEW                32819
#define MENU_SCALEUP_VIEW               32821
#define MENU_VIRTUAL_MOUNT              32823
#define MENU_DESIGN_INPUT               32824
#define MENU_DESIGN_DELETE              32825
#define MENU_DESIGN_INPUT_MESSAGE       32826
#define MENU_DESIGN_MAIN_SORT           32827
#define MENU_DESIGN_SUB_SORT            32829
#define MENU_SAVE_MOVEMENT              32830
#define MENU_RESTORE_MOVEMENT           32833
#define MENU_MOVE_MOVEMENT              32835
#define MENU_COMBINE_STEP               32838
#define MENU_SEPARATE_STEP              32839
#define MENU_CREATE_SOUND_FILE          32841
#define MENU_CYCLE_MOUNT                32842
#define MENU_MOUNT_PROGRESS_TABLE       32843
#define MENU_SUB_STEP_INCREASE          32849
#define MENU_SUB_STEP_DECREASE          32850
#define MENU_MAIN_STEP_INCREASE         32851
#define MENU_MAIN_STEP_DECREASE         32852
#define MENU_CURRENT_MOUNT_STEP         32853
#define MENU_CACHE_INSERT_OR_DELETE     32855
#define MENU_CACHE_SUB_INCREASE_MODE    32870
#define MENU_CACHE_SUB_DECREASE_MODE    32871
#define MENU_CACHE_SUB_REMAIN_MODE      32872
#define MENU_CACHE_MAIN_DECREASE_MODE   32873
#define MENU_CACHE_MAIN_REMAIN_MODE     32874
#define MENU_CACHE_MAIN_INCREASE_MODE   32875
#define MENU_HIDE_ALL_COMPONENT_EXCEPT_IN_SMALL_WINDOW 32877
#define MENU_FORWARD_BIG                32878
#define MENU_BACKWARD_BIG               32879
#define MENU_SELECT_BRDGE               32880
#define MENU_SELECT_BRIDGE              32881
#define MENU_SET_MANUAL_MOUNT           32883
#define MENU_INTERACT_BOX_DISTANCE      32884
#define MENU_MOUNT_PART_TABLE           32886
#define MENU_DISPLAY_REFERENCE_FRAME    32887
#define ID_32888                        32888
#define ID_32889                        32889
#define MENU_TREE_MOVEMENT_SAVE_TO_CACHE 32890
#define MENU_MANUAL                     32928
#define MENU_MANUAL_VIEW                32929

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        340
#define _APS_NEXT_COMMAND_VALUE         32934
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
