#define MAX_LIGHT_NUMBER				4
#define MAX_CLIP_PLANE_NUMBER			8

#define	MAX_OBJECT_TYPE_ID				5

#define MAX_BUFFER_LENGTH				2000

#define MAX_CAMERA_NUMBER				9
#define MAX_CAMERA_RETREAT_NUMBER		1000

#define MAX_PART_NUMBER					1000
#define MAX_COMPONENT_NUMBER			100000

#define MAX_SHADER_PROGRAM_NUMBER		1000

#define MIN_VALUE						(1.0/1000.0/1000.0/1000.0)

#define MAX_SHADER_NUMBER				5


#define MAX_NETWORK_BUFFER_LENGTH		1024*1024

#define MAX_CACHE_MOVEMENT_NUMBER		25000
#define BEGIN_RIGHT_BUTTON_COMMOND_ID	40000
#define END_RIGHT_BUTTON_COMMOND_ID		(BEGIN_RIGHT_BUTTON_COMMOND_ID+MAX_CACHE_MOVEMENT_NUMBER)

